# Site settings
title: 'Codeherb'
email: hiddenkit@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yakcho's Developer Story
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://codeherb.github.io" # the base hostname & protocol for your site
remote_theme: volny/creative-theme-jekyll

twitter_username:
github_username: codeherb

# Build settings
markdown: kramdown
